model_id: "Ensemble-MAP-Adam_1_M1024"
epoch: 150
M: 1024
optimizer: asgld.ASGLD
accept_model: False
optim.Adam:
  lr: 1.e-3
asgld.ASGLD:
  lr: 9.e-3
  momentum: .9
  weight_decay: 5.e-4
  eps: 1.e-6
  noise: 1.e-2